source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableViewManager_Example', :exclusive => true do
  pod 'TableViewManager', :path => '../'
end

target 'TableViewManager_Tests', :exclusive => true do
  pod 'TableViewManager', :path => '../'

  
end
