source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TableViewDataManager_Example', :exclusive => true do
  pod 'TableViewDataManager', :path => '../'
end

target 'TableViewDataManager_Tests', :exclusive => true do
  pod 'TableViewDataManager', :path => '../'

  
end
